services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema_folha_api
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistema_folha
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-prod
      args:
        VITE_API_URL: http://10.113.134.159:8083/api
    container_name: sistema_folha_frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  postgres:
    image: postgres:15-alpine
    container_name: sistema_folha_db
    environment:
      POSTGRES_DB: sistema_folha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 