spring:
  application:
    name: sistema-folha
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_folha
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:techne_engenharia_sistemas_ltda_50_737_766_0001_21}
  expiration: 86400000 # 24 horas em milissegundos 